project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/lisamr/website
  repo-actions: [source]
  title: Home
  navbar:
    right:
      - text: 'Blog'
        href: blog.qmd
      - text: 'Projects'
        href: projects.qmd 
      - text: 'Resume'
        href: resume.qmd
      - text: 'Fun'
        href: fun.qmd
      - icon: github
        href: https://github.com/lisamr
      - icon: linkedin
        href: https://www.linkedin.com/in/lisamr/
format:
  html:
    theme: lux
    css: styles.css


