project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [source]
  title: Home
  navbar:
    right:
      - text: 'Fun'
      - text: 'Projects'
        menu: 
          - text: 'grad work'
      - text: 'Blog'
        href: blog.qmd
      - icon: github
        href: https://github.com/lisamr
      - icon: linkedin
        href: https://www.linkedin.com/in/lisamr/
format:
  html:
    theme: lux
    css: styles.css


